name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # --- CI: линт, тесты и сборка ---
  test-and-build:
    name: Test, Lint and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --force

      - name: Run Linter
        run: npm run lint

      - name: Build Package
        run: npm run build

  # --- Security: уязвимости, статический анализ и секреты ---
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --force

      # Проверка зависимостей на уязвимости
      - name: NPM Audit (prod dependencies only)
        run: npm audit --audit-level=high --omit=dev

      # CodeQL анализ (инициализация)
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript

      # CodeQL анализ (запуск)
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      # Поиск утечек секретов
      - name: Secret Scanning with TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
        continue-on-error: true
