name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: rm -rf docs && npm run build-storybook

      - name: Commit and Push Storybook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs -f
          git commit -m "chore: update storybook [skip ci]" || echo "No changes to commit"
          # подтягиваем свежие изменения и делаем безопасный push
          git pull --rebase origin main
          git push origin main --force-with-lease
